### ISSUE TITLE
Cura Profile

### ISSUE THREAD

**Issue by Zorgonaute84** [BCN3D/BCN3D-Utilities#1]
The profil in the folder are only for single extrusion.

Attached, you can find my proposal for dual extrusion.

The printer profil have to be move into the definition folder, and the both extruders profil have to be copy into the extruders folder.

[Cura profil for IDEX.zip](https://github.com/BCN3D/BCN3D-Utilities/files/557162/Cura.profil.for.IDEX.zip)

**Comment by Zorgonaute84** [comment]
Is it schedule to share with ultimaker the profil of the BCN3D Sigma ? They told that they can include custom profil into the next Cura release if the manufacturer have contact with them... What is the position of BCN3D about that ?

**Comment by Zorgonaute84** [comment]
Up !

**Comment by trancept** [comment]
Hello, any news ?
You are close to have a one year old issue...
I'd like to help but could you share where you are now ?

**Comment by guillemavila** [comment]
Hello, sorry we completely missed this issue. 

You can find all our profiles for ultimaker's Cura 2.7 [here](https://github.com/BCN3D/BCN3D-Utilities/tree/master/Sigma%20-%20Cura%202), and also test our new BCN3D Cura [here](https://drive.google.com/file/d/0B9EhngnR5bl6N1Q1cXFzTkpfazQ/view) (with our latest profiles included).
